name: base64_tool
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: 8.1.3
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  fpdart: 1.1.0
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.10+1
  hooks_riverpod: 2.5.1
  intl: 0.19.0
  responsive_framework: 1.4.0
  riverpod_annotation: 2.3.5
  talker_flutter: 4.3.2
  toastification: 2.0.0
  freezed_annotation: 2.4.1
  window_manager: 0.3.9
  animated_toggle_switch: 0.8.2
  talker_riverpod_logger: 1.1.2
  objectbox: 4.0.1
  objectbox_flutter_libs: 4.0.1
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  auto_route_generator: 8.0.0
  build_runner: 2.4.10
  custom_lint: any
  flutter_gen_runner: 5.5.0+1
  freezed: 2.5.3
  lint: 2.3.0
  riverpod_generator: 2.4.2
  riverpod_lint: 2.3.12
  objectbox_generator: 4.0.1
  source_gen: 1.5.0

dependency_overrides:
  meta: 1.14.0

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: 'ic_launcher'
  ios: false
  image_path: 'assets/images/png/ic_launcher.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
